server {
  listen 80;

  # Gzip Compression
  gzip on;
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_min_length 256;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
  
  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  # Cache static assets
  location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|woff2)$ {
    root /usr/share/nginx/html;
    expires 30d;
    add_header Cache-Control "public, no-transform";
  }

  location /api/ {
    proxy_pass http://backend:5000;
  }
}

